#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
#
# chkconfig:   - 85 15 
# description: redis init script
# processname: redis_6379
#
REDISPORT=6379
EXEC=/usr/local/sbin/redis-server
CLIEXEC=/usr/local/bin/redis-cli

PIDFILE=/var/run/redis_${REDISPORT}.pid
CONF="/etc/redis/${REDISPORT}.conf"

start()
	{
	
	if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
	}

stop ()
	{
	if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $REDISPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
	}

status()
        {
	if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "redis-server is NOT running."
                exit 1
        fi
        }

restart ()
	{
	stop
	start
	} 


case "$1" in
    start) start
        ;;
    stop)  stop
        ;;
    status) status
	;;
    restart) restart
	;;
    *)
        echo "Please use start|stop|restart as first argument"
        ;;
esac
